# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0019_auto_20180127_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='mdn',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mdn',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mdn',
            name='status',
            field=models.CharField(choices=[(b'S', 'Sent'), (b'R', 'Received'), (b'P', 'Pending'), (b'E', 'Error')], max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
